src/MG/UserBundle/Entity/Image.php
<?php

namespace MG\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * 
 */
class Image
{
    
  /**
   * 
   */
  private $id;

  /**
   * 
   */
  private $extension;

  /**
   * 
   */
  private $alt;

  /**
   * @Assert\File(maxSize="4M")
   */
  private $file;

  private $filename;
  
  /**
   * PrePersist & PreUpdate
   */
  public function preUpload()
  {   
    if (null === $this->file) {
      return;
    }
    
    $this->extension = $this->file->guessExtension();
    
    if(null === $this->alt) {
        $this->alt = $this->file->getClientOriginalName();
    }
  }

  /**
   * PostPersist & PostUpdate
   */
  public function upload()
  {
    if (null === $this->file) {
      return;
    }

    // Si il y a un ancien fichier 
    if (null !== $this->filename) {
      $oldFile = $this->getPhpDir().'/'.$this->id.'.'.$this->filename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }

    $this->file->move(
      $this->getPhpDir(), 
      $this->id.'.'.$this->extension   
    );
  }

  /**
   * PreRemove
   */
  public function preRemoveUpload()
  {
    // Sauvegarde temporaire du nom de fichier car il dépend de l'id
    $this->filename = $this->getPhpDir().'/'.$this->id.'.'.$this->extension;
  }

  /**
   * PostRemove
   */
  public function removeUpload()
  {
    if (file_exists($this->filename)) {
      unlink($this->filename);
    }
  }

  public function getWebDir()
  {
    return 'uploads/img';
  }

  public function getPhpDir()
  {
    return __DIR__.'/../../../../web/'.$this->getWebDir();
  }

  public function getWebPath()
  {
    return '/'.$this->getWebDir().'/'.$this->getId().'.'.$this->getExtension();
  }

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @param string $extension
   * @return Image
   */
  public function setExtension($extension)
  {
    $this->extension = $extension;
    return $this;
  }

  /**
   * @return string
   */
  public function getExtension()
  {
    return $this->extension;
  }

  /**
   * @param string $alt
   * @return Image
   */
  public function setAlt($alt)
  {
    $this->alt = $alt;
    return $this;
  }

  /**
   * @return string
   */
  public function getAlt()
  {
    return $this->alt;
  }

  public function setFile($file)
  {
    $this->file = $file;

    // Si il y avait déjà un fichier pour cette entité
    if (null !== $this->extension) {
      // sauvegarde de l'extension du fichier pour le supprimer
      $this->filename = $this->extension;

      
      // Réinitialisation des valeurs des attributs extension et alt
      $this->extension = null;
      $this->alt = null;
    }
    return $this;
  }

  public function getFile()
  {
    return $this->file;
  }
}

src/MG/UserBundle/Resources/views/Admin/is_not_validate_applicants.html.twig
{#{% extends "CVThequeBundle::layout.html.twig" %}#}
{% extends '::base.html.twig' %}

{% block title %}
    Applicants non validés
{% endblock %}

{% block bandeau %}
    <div class="row">
        <h1>Profils étudiants non validés</h1>
        <div class="lead">Liste des profils étudiants <b>non validés</b> par un administrateur.</div>
    </div>
{% endblock %}

{% block content %}

    <div class="list-user w-avatar container">
        {% for applicant in applicants %}
            
            <a class="bloc list-user-row row" href="{{ path('mg_user_profile_visite', {'slug': applicant.slug}) }}">
                <div class='col-md-1 user-avatar'>
                    <img {% if applicant.image is not null %}src="{{ applicant.image.webPath }}" alt="{{ applicant.image.alt }}"{% endif %} />
                </div>
                <div class='col-md-4 user-name'>
                    <span class='user-lastname'>{{ applicant.lastname }}</span> 
                    <span class='user-firstname'>{{ applicant.firstname }}</span> 
                    <span class='user-username'>{{ applicant.username }}</span>
                </div>
                <div class='col-md-2 user-category'>
                    <span class='tag'>{% if applicant.category is not null %}{{ applicant.category.name }}{% endif %}</span>
                </div>
                <div class='col-md-1'>
                    <span class='icon-bloc {% if applicant.cvFile is null %}error{% else %}primary{% endif %}'>
                        CV
                        <span class='spinner-box'>
                            <span class='icon l-white glyphicon {% if applicant.cvFile is null %}glyphicon-remove{% else %}glyphicon-ok{% endif %}'></span>
                        </span>
                    </span>
                </div>
                <div class='col-md-1'>
                    <span class='icon-bloc {% if applicant.logBookFile is null %}error{% else %}primary{% endif %}'>
                        Journal
                        <span class='spinner-box'>
                            <span class='icon l-white glyphicon {% if applicant.logBookFile is null %}glyphicon-remove{% else %}glyphicon-ok{% endif %}'></span>
                        </span>
                    </span>
                </div>
                <div class='col-md-3'>
                    Créé le {{ applicant.created|date('d/m/Y') }}, màj le {{ applicant.updated|date('d/m/Y') }}
                </div>
            </a>
                
        {% else %}
            <div class="bloc list-user-row row text-center">
                Il n'y a aucun profil étudiant non validé.
            </div>
        {% endfor %}
    </div>
    {% if nb_page > 1 %}
        <div class="text-center">
            <ul class="pagination">
                {% for p in range(1, nb_page) %}
                    {% if p == page %}
                        <li class="active">
                            <span>{{ p }}</span>
                        </li>
                        {% else %}
                        <li>
                            <a href="{{ path('mg_admin_show_applicants_not_validate', {'page': p}) }}">{{ p }}</a>
                        </li>
                        {% endif %} 
                    {% endfor %}
            </ul>
        </div>
    {% endif %} 
{% endblock %}

src/MG/UserBundle/Resources/views/Admin/is_validate_applicants.html.twig
{#{% extends "CVThequeBundle::layout.html.twig" %} #}
{% extends '::base.html.twig' %}

{% block title %}
    Applicants validés
{% endblock %}

{% block bandeau %}
    <div class="row">
        <h1>Profils étudiants validés</h1>
        <div class="lead">Liste des profils étudiants <b>validés</b> par un administrateur.</div>
    </div>
{% endblock %}

{% block content %}

    <div class="list-user w-avatar container">
        {% for applicant in applicants %}

            <a class="bloc list-user-row row" href="{{ path('mg_user_profile_visite', {'slug': applicant.slug}) }}">
                <div class='col-md-1 user-avatar'>
                    <img {% if applicant.image is not null %}src="{{ applicant.image.webPath }}" alt="{{ applicant.image.alt }}"{% endif %} />
                </div>
                <div class='col-md-4 user-name'>
                    <span class='user-lastname'>{{ applicant.lastname }}</span> 
                    <span class='user-firstname'>{{ applicant.firstname }}</span> 
                    <span class='user-username'>{{ applicant.username }}</span>
                </div>
                <div class='col-md-2 user-category'>
                    <span class='tag'>{% if applicant.category is not null %}{{ applicant.category.name }}{% endif %}</span>
                </div>
                <div class='col-md-1'>
                    <span class='icon-bloc {% if applicant.cvFile is null %}error{% else %}primary{% endif %}'>
                        CV
                        <span class='spinner-box'>
                            <span class='icon l-white glyphicon {% if applicant.cvFile is null %}glyphicon-remove{% else %}glyphicon-ok{% endif %}'></span>
                        </span>
                    </span>
                </div>
                <div class='col-md-1'>
                    <span class='icon-bloc {% if applicant.logBookFile is null %}error{% else %}primary{% endif %}'>
                        Journal
                        <span class='spinner-box'>
                            <span class='icon l-white glyphicon {% if applicant.logBookFile is null %}glyphicon-remove{% else %}glyphicon-ok{% endif %}'></span>
                        </span>
                    </span>
                </div>
                <div class='col-md-3'>
                    Créé le {{ applicant.created|date('d/m/Y') }}, màj le {{ applicant.updated|date('d/m/Y') }}
                </div>
            </a>

        {% else %}
            <div class="bloc list-user-row row text-center">
                Il n'y a aucun profil étudiant non validé.
            </div>
        {% endfor %}
    </div>
    {% if nb_page > 1 %}
        <div class="text-center">
            <ul class="pagination">
                {% for p in range(1, nb_page) %}
                    {% if p == page %}
                        <li class="active">
                            <span>{{ p }}</span>
                        </li>
                    {% else %}
                        <li>
                            <a href="{{ path('mg_admin_show_applicants_validate', {'page': p}) }}">{{ p }}</a>
                        </li>
                    {% endif %} 
                {% endfor %}
            </ul>
        </div>
    {% endif %} 
{% endblock %}

src/MG/UserBundle/Resources/views/Admin/societys.html.twig
{#{% extends "CVThequeBundle::layout.html.twig" %} #}
{% extends '::base.html.twig' %}

{% block title %}
    Liste des entreprises
{% endblock %}

{% block bandeau %}
    <div class="row">
        <h1>Profils entreprises</h1>
        <div class="lead">Liste des entreprises</div>
    </div>
{% endblock %}

{% block content %}

    <div class="list-user w-avatar container">
        {% for society in societys %}

            <a class="bloc list-user-row row" href="{{ path('mg_user_profile_visite', {'slug': society.slug}) }}">
                <div class='col-md-1 user-avatar'>
                    <img {% if society.image is not null %}src="{{ society.image.webPath }}" alt="{{ society.image.alt }}"{% endif %} />
                </div>
                <div class='col-md-4 user-name'>
                    <span class='user-lastname'>{{ society.societyName }}</span> 
                    <span class='user-username'>{{ society.username }}</span>
                </div>
                <div class='col-md-2 user-category'>
                    <span class='tag'>{% if society.category is not null %}{{ society.category.name }}{% endif %}</span>
                </div>
                <div>
                    Créé le {{ society.created|date('d/m/Y') }}, màj le {{ society.updated|date('d/m/Y') }}
                </div>
            </a>

        {% else %}
            <div class="bloc list-user-row row text-center">
                Il n'y a aucun profil entreprise.
            </div>
        {% endfor %}
    </div>
    {% if nb_page > 1 %}
        <div class="text-center">
            <ul class="pagination">
                {% for p in range(1, nb_page) %}
                    {% if p == page %}
                        <li class="active">
                            <span>{{ p }}</span>
                        </li>
                    {% else %}
                        <li>
                            <a href="{{ path('mg_admin_show_societys', {'page': p}) }}">{{ p }}</a>
                        </li>
                    {% endif %} 
                {% endfor %}
            </ul>
        </div>
    {% endif %} 
{% endblock %}